title: Kernel Latency Tracker in LTTNG
url: torsho.me/lttng-latency-tracker-report-2022-oct
remote_theme: pages-themes/hacker
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - lttng.md
